openapi: 3.0.0
info:
  title: AI Social Assistant API
  version: 1.0.0
  description: API quản lý kênh, nội dung, job tự động cho mạng xã hội

servers:
  - url: /api/v1

paths:
  /auth/register:
    post:
      summary: Register new user
      operationId: registerUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'

  /auth/authenticate:
    post:
      summary: Login user
      operationId: loginUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'

  /auth/logout:
    post:
      summary: Logout user
      operationId: logoutUser
      tags:
        - Auth
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    UserRequest:
      type: object
      required:
        - username
        - password
        - email
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
        visibleName:
          type: string

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    AuthenticationResponse:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        token:
          type: string
        roles:
          type: array
          items:
            type: string
