openapi: "3.0.0"
info:
  title: Ai Social Assistant - User API
  version: "1.0.0"
  description: API quản lý User trong dự án Ai Social Assistant

servers:
  - url: /api/v1
    description: Local server

tags:
  - name: Users
    description: Quản lý người dùng
  - name: Auth
    description: Xác thực người dùng

paths:

  /auth/register:
    post:
      tags:
        - Auth
      summary: Đăng ký người dùng mới
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '400':
          description: Dữ liệu không hợp lệ

  /auth/authenticate:
    post:
      tags:
        - Auth
      summary: Đăng nhập
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '401':
          description: Username hoặc password không đúng

  /auth/logout:
    post:
      tags:
        - Auth
      summary: Đăng xuất
      responses:
        '200':
          description: Logout thành công

  /users:
    get:
      tags:
        - Users
      summary: Lấy danh sách người dùng
      responses:
        '200':
          description: Danh sách người dùng
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'

    post:
      tags:
        - Users
      summary: Tạo mới người dùng
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Tạo thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'

  /users/{userId}:
    get:
      tags:
        - Users
      summary: Lấy thông tin người dùng theo ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Thông tin người dùng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: Người dùng không tồn tại

components:
  schemas:
    UserRequest:
      type: object
      required:
        - username
        - password
        - email
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
        visibleName:
          type: string

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    UserResponse:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        visibleName:
          type: string
        status:
          type: string

    AuthenticationResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: '#/components/schemas/UserResponse'
